version: "3.7"

services:

  service_1:
    build: ./service_1
    container_name: service_1
    ports:
      - "8001:8001"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8001/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  service_2:
    build: ./service_2
    container_name: service_2
    ports:
      - "8002:8002"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 30s
      timeout: 10s
      retries: 6

  nginx_reverse_proxy:
    build: ./nginx
    container_name: nginx_reverse_proxy
    depends_on:
      service_1:
        condition: service_healthy
      service_2:
        condition: service_healthy
    ports:
      - "8085:80"
    networks:
      - backend

 

networks:
  backend:
